### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by maxpain** [join-monster/join-monster#134]
Join-monster version: 1.2.1-beta.9

Error:
```javascript
TypeError: Cannot read property '0' of undefined
    at /Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/batch-planner/index.js:76:90
    at Generator.next (<anonymous>)
    at step (/Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/batch-planner/index.js:19:191)
    at /Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/batch-planner/index.js:19:361
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Query:
```graphql
{
  match(id: 35) {
    members {
      user {
        stats(gameID: 1) {
          id
        }
      }
    }
  }
}
```

Schema:
```javascript
const Match = new GraphQLObjectType({
	name: 'Match',
	sqlTable: 'matches',
	uniqueKey: 'id',
	fields: () => ({
		id: { type: new GraphQLNonNull(GraphQLID) },
		members: {
			type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(MatchMember))),
			sqlBatch: {
				thisKey: 'match_id',
				parentKey: 'id'
			}
		}
	})
})

const MatchMember = new GraphQLObjectType({
	description: 'A match member type',
	name: 'MatchMember',
	sqlTable: 'match_members',
	uniqueKey: ['match_id', 'user_id'],
	fields: () => ({
		id: {
			type: new GraphQLNonNull(GraphQLID),
			sqlDeps: ['match_id', 'user_id'],
			resolve: m => `${m.match_id}_${m.user_id}`
		},
		user: {
			type: new GraphQLNonNull(User),
			sqlJoin: (matchMembersTable, usersTable) =>
				`${usersTable}.id = ${matchMembersTable}.user_id`
		}
	})
})

const User = new GraphQLObjectType({
	description: 'A user type',
	name: 'User',
	sqlTable: 'users',
	uniqueKey: 'id',
	fields: () => ({
		id: {
			type: new GraphQLNonNull(GraphQLID)
		},
		stats: {
			type: UserStats,

			args: {
				gameID: { type: new GraphQLNonNull(GraphQLID) }
			},

			sqlBatch: {
				thisKey: 'user_id',
				parentKey: 'id'
			},

			where: (table, { gameID }) => `${table}.game_id = ${+gameID}`
		},
	})
})

const UserStats = new GraphQLObjectType({
	name: 'UserStats',
	description: 'A user stats type',
	sqlTable: 'user_stats',
	uniqueKey: ['user_id', 'game_id'],

	fields: () => ({
		id: {
			type: new GraphQLNonNull(GraphQLID),
			sqlDeps: ['user_id', 'game_id'],
			resolve: s => `${s.user_id}_${s.game_id}`
		},
		rating: { type: new GraphQLNonNull(GraphQLInt) },
		place: { type: GraphQLInt }
	})
})
```

**Comment by marazt** [comment]
I found similar problem (versions 1.2.1-beta.2 and 1.2.4-beta.1):
A query with selector on C fails:
```GraphQL
{
  a {
    id
    b {
      id
      c (id: 1) {
        id
      }
    }
  }
}
```
A query without selector on C is running fine:
```GraphQL
{
  a {
    id
    b {
      id
      c {
        id
      }
    }
  }
}
```

Schemas:
```TypeScript
const A: GraphQLObjectType = new GraphQLObjectType({
  name: 'A',
  sqlTable: 'public."a"',
  uniqueKey: 'id',
  fields: () => ({
    id: {
      description: 'A id',
      type: new GraphQLNonNull(GraphQLID)
    },
    b: {
      description: 'b',
      type: B,
      sqlBatch: {
        thisKey: 'id',
        parentKey: 'id'
      }
    }
  })
})
```

```TypeScript
const B: GraphQLObjectType = new GraphQLObjectType({
  name: 'B',
  sqlTable: 'public."a"', // yes, A and B query the same table
  uniqueKey: 'id',
  fields: () => ({
    id: {
      description: 'B id',
      type: new GraphQLNonNull(GraphQLID)
    },
    c: {
      description: 'C',
      type: C,
       args: {
        id: {
          description: 'C id',
          type: GraphQLID
        }
      },
      sqlJoin(bTable: {c_id: number}, cTable: {id: number}): string {
        return `${bTable}.c_id = ${cTable}.id`
      },
      where: (cTable,  args) => {
        if (args.id != null) { // it seems that this causes the problem even the generated SQL query looks ok
          return `${cTable}.id = '${args.id}'`
        }
        return null
      }
    }
})
```
```TypeScript
const C: GraphQLObjectType = new GraphQLObjectType({
  name: 'C',
  sqlTable: 'public."c"',
  uniqueKey: 'id',
  fields: () => ({
    id: {
      description: 'C id',
      type: new GraphQLNonNull(GraphQLID)
    }
  })
})
```

When I check the generated SQL query and test it, it works fine, i.e., returns expected data

**Comment by marazt** [comment]
Hi, I have created a pull request #137 with a fix. Hope it is correct.

**Comment by acarl005** [comment]
Thanks @marazt! New version is published.
