### ISSUE TITLE
Relay Modern Support

### ISSUE THREAD

**Issue by gardner** [join-monster/join-monster#168]
What is the appropriate fit for Relay Modern and Join Monster?

I tried serializing the output of a `GraphQLSchema` instance to json but received undefined errors.

Here is the schema.json which was generated from the join-monster-demo pagination-schema using:

```js
import schemaRelay from './schema-paginated/index'
console.log(JSON.stringify(schemaRelay))
```
 And the output:
```json
{
    "_directives": [
        {
            "args": [
                {
                    "description": "Included when true.",
                    "name": "if",
                    "type": "Boolean!"
                }
            ],
            "description": "Directs the executor to include this field or fragment only when the `if` argument is true.",
            "locations": [
                "FIELD",
                "FRAGMENT_SPREAD",
                "INLINE_FRAGMENT"
            ],
            "name": "include"
        },
        {
            "args": [
                {
                    "description": "Skipped when true.",
                    "name": "if",
                    "type": "Boolean!"
                }
            ],
            "description": "Directs the executor to skip this field or fragment when the `if` argument is true.",
            "locations": [
                "FIELD",
                "FRAGMENT_SPREAD",
                "INLINE_FRAGMENT"
            ],
            "name": "skip"
        },
        {
            "args": [
                {
                    "defaultValue": "No longer supported",
                    "description": "Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted in [Markdown](https://daringfireball.net/projects/markdown/).",
                    "name": "reason",
                    "type": "String"
                }
            ],
            "description": "Marks an element of a GraphQL schema as no longer supported.",
            "locations": [
                "FIELD_DEFINITION",
                "ENUM_VALUE"
            ],
            "name": "deprecated"
        }
    ],
    "_implementations": {
        "Node": [
            "User",
            "Post",
            "Comment"
        ]
    },
    "_queryType": "Query",
    "_typeMap": {
        "Boolean": "Boolean",
        "Comment": "Comment",
        "CommentConnection": "CommentConnection",
        "CommentEdge": "CommentEdge",
        "Float": "Float",
        "ID": "ID",
        "Int": "Int",
        "LuckyNumber": "LuckyNumber",
        "Node": "Node",
        "PageInfo": "PageInfo",
        "Post": "Post",
        "PostConnection": "PostConnection",
        "PostEdge": "PostEdge",
        "Query": "Query",
        "SimpleComment": "SimpleComment",
        "String": "String",
        "User": "User",
        "UserConnection": "UserConnection",
        "UserEdge": "UserEdge",
        "__Directive": "__Directive",
        "__DirectiveLocation": "__DirectiveLocation",
        "__EnumValue": "__EnumValue",
        "__Field": "__Field",
        "__InputValue": "__InputValue",
        "__Schema": "__Schema",
        "__Type": "__Type",
        "__TypeKind": "__TypeKind"
    },
    "astNode": null
}
```

Which throws:
```
$ ./node_modules/.bin/relay-compiler --src ./src --schema ./schema.json 
HINT: pass --watch to keep watching for changes.
Parsed default in 0.00s

Writing default
Error: Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

TypeError: Cannot read property '__schema' of undefined
    at buildClientSchema (/Users/gardner/src/demo/modern/node_modules/graphql/utilities/buildClientSchema.js:48:42)
    at _getSchema (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:181:29)
    at Object.getSchema (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:103:19)
    at RelayCodegenRunner.<anonymous> (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:4749:48)
    at next (native)
    at step (/Users/gardner/src/demo/modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/gardner/src/demo/modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/gardner/src/demo/modern/node_modules/core-js/library/modules/_export.js:35:28)
    at RelayCodegenRunner.<anonymous> (/Users/gardner/src/demo/modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at RelayCodegenRunner.write (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:4829:21)
    at _getSchema (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:186:12)
    at Object.getSchema (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:103:19)
    at RelayCodegenRunner.<anonymous> (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:4749:48)
    at next (native)
    at step (/Users/gardner/src/demo/modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/gardner/src/demo/modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at Promise.F (/Users/gardner/src/demo/modern/node_modules/core-js/library/modules/_export.js:35:28)
    at RelayCodegenRunner.<anonymous> (/Users/gardner/src/demo/modern/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at RelayCodegenRunner.write (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:4829:21)
    at RelayCodegenRunner.<anonymous> (/Users/gardner/src/demo/modern/node_modules/relay-compiler/bin/relay-compiler:4653:41)

**Comment by acarl005** [comment]
Was it working *without* join monster? I don't think thats the problem.  Join monster does not alter the schema itself.

**Comment by gardner** [comment]
Sorry about that. This was just me not understanding that `relay-compiler` should be run on client queries.
