### ISSUE TITLE
how to use graphqlobject instead of  junction ?

### ISSUE THREAD

**Issue by fangjj** [join-monster/join-monster#219]
I new graphqlobject instead of junction, but got a error, how can i do ? I read doc in join-monster, just said The first is to create a GraphQLObjectType for the  relationships table. This table could become an interleaving Relationship type instead of using Join Monster's junction option. so, I'm lost. 
```javascript
const RelationLikes = new GraphQLObjectType({
  description: 'a likes',
  name: "RelationLikes",
  sqlTable: 'likes',
  uniqueKey: ['account_id', 'comment_id'],
  fields: {
    users: {
      type: new GraphQLList(User),
      sqlJoin: (likesTable, userTable) => `${likesTable}.account_id = ${userTable}.id`
    },
    comments: {
      type: new GraphQLList(Comment),
      sqlJoin: (likesTable, commentTable) => `${likesTable}.comment_id = ${commentTable}.id`
    },
    account_id: {
      type: GraphQLInt
    },
    comment_id: {
      type: GraphQLInt
    },
    created_at: {
      type: GraphQLString
    },
  }
});

const User = new GraphQLObjectType({
  //...
  fields: {
  	relationLikes: {
      description: "RelationLikes",
      type: new GraphQLList(RelationLikes),
      sqlJoin: (userTable, likesTable) => `${userTable}.id = ${likesTable}.account_id`
    },
  }
});

const Comment = new GraphQLObjectType({
  //...
  fields: {
  	relationLikes: {
      description: "comments likes",
      type: new GraphQLList(RelationLikes),
      sqlJoin: (commentTable, likesTable) => `${commentTable}.id = ${likesTable}.comment_id`
    },
  }
});

```
```javascript
npm start

> join-monster-demo@1.0.0 start /Users/jm/Documents/jm/relay/join-monster-demo
> babel-node server.js

/Users/jm/Documents/jm/relay/join-monster-demo/node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
    ^

Error: Can only create List of a GraphQLType but got: undefined.
    at invariant (/Users/jm/Documents/jm/relay/join-monster-demo/node_modules/graphql/jsutils/invariant.js:19:11)
    at new GraphQLList (/Users/jm/Documents/jm/relay/join-monster-demo/node_modules/graphql/type/definition.js:696:29)
    at Object.<anonymous> (/Users/jm/Documents/jm/relay/join-monster-demo/schema-basic/RelationLikes.js:17:13)
    at Module._compile (module.js:570:32)
    at loader (/Users/jm/Documents/jm/relay/join-monster-demo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jm/Documents/jm/relay/join-monster-demo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jm/Documents/jm/relay/join-monster-demo/schema-basic/Comment.js:12:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/jm/Documents/jm/relay/join-monster-demo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jm/Documents/jm/relay/join-monster-demo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
```

**Comment by acarl005** [comment]
This error `Can only create List of a GraphQLType but got: undefined` is not a join-monster error, but from the `graphql` module. You've passed `undefined` to the `GraphQLList` constructor. You can forego join-monster's junction options by making the junction table its own `GraphQLObjectType` in your schema. That is, however, not related to this error message.

**Comment by fangjj** [comment]
yeah, thanks. I know why. just use thunk fileds in User and RelationLikes.
```javascript
const RelationLikes = new GraphQLObjectType({
  description: 'a likes',
  name: "RelationLikes1",
  sqlTable: 'likes',
  uniqueKey: ['account_id', 'comment_id'],
  fields: () => ({
    
    user: {
      type: User,
      sqlJoin: (likesTable, userTable) => `${likesTable}.account_id = ${userTable}.id`
    },
    
    comment: {
      type: Comment,
      sqlJoin: (likesTable, commentTable) => `${likesTable}.comment_id = ${commentTable}.id`
    },
    account_id: {
      type: GraphQLInt,
      sqlColumn: 'account_id'
    },
    comment_id: {
      type: GraphQLInt,
      sqlColumn: 'comment_id'
    },
    created_at: {
      type: GraphQLString,
      sqlColumn: 'created_at'
    },
  })
});
```
