### ISSUE TITLE
Batch bug

### ISSUE THREAD

**Issue by maxpain** [join-monster/join-monster#268]
GraphQL query:
```graphql
{
  league(gameID: 2, regionID: 1) {
    id
    seasons {
      id
      usersTop(ratingGroupID: 1) {
        edges {
          node {
            id
          }
        }
      }
    }
  }
}
```

Schema:
```es6
const LeagueSeason = new GraphQLObjectType({
	name: 'LeagueSeason',
	sqlTable: 'league_seasons',
	uniqueKey: 'id',
	fields: () => ({
		id: { type: new GraphQLNonNull(GraphQLID) },
		usersTop: {
			type: LeagueSeasonUserStatsConnection,
			args: {
				...connectionArgs,
				ratingGroupID: { type: new GraphQLNonNull(GraphQLID) }
			},
			sqlBatch: {
				thisKey: 'season_id',
				parentKey: 'id'
			},
			orderBy: {
				rating: 'DESC'
			},

			where: (stats, { ratingGroupID }) =>
				`${stats}.rating_group_id = ${+ratingGroupID}`,

			resolve: (root, args, context, resolveInfo) =>
				joinMonster(resolveInfo, context)
		}
	})
})

const LeagueSeasonUserStats = new GraphQLObjectType({
	name: 'LeagueSeasonUserStats',
	sqlTable: 'league_season_user_stats',
	uniqueKey: ['season_id', 'user_id'],
	fields: () => ({
		id: {
			type: new GraphQLNonNull(GraphQLID),
			sqlDeps: ['season_id', 'user_id'],
			resolve: s => `${s.season_id}_${s.user_id}`
		},
		ratingGroup: {
			type: LeagueRatingGroup,
			sqlJoin: (stats, ratingGroups) =>
				`${ratingGroups}.id = ${stats}.rating_group_id`
		},
		user: {
			type: new GraphQLNonNull(User),
			sqlJoin: (stats, users) =>
				`${users}.id = ${stats}.user_id`
		},
		rating: { type: new GraphQLNonNull(GraphQLFloat) },
		place: { type: GraphQLInt }
	})
})

const { connectionType: LeagueSeasonUserStatsConnection } = connectionDefinitions({ nodeType: LeagueSeasonUserStats })
```

Error:

```javascript
TypeError: Cannot read property 'join' of undefined
    at /Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/stringifiers/dispatcher.js:162:86
    at Generator.next (<anonymous>)
    at step (/Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/stringifiers/dispatcher.js:192:191)
    at /Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/stringifiers/dispatcher.js:192:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Logs:
```javascript
join-monster SQL_AST
  join-monster  { args: { gameID: '2', regionID: '1' },
  type: 'table',
  name: 'leagues',
  as: 'league',
  children:
   [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
     SQLASTNode { args: {}, type: 'column', name: 'id', fieldName: 'id', as: 'id' },
     SQLASTNode {
       args: {},
       type: 'table',
       name: 'league_seasons',
       as: 'seasons',
       children:
        [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
          SQLASTNode { args: {}, type: 'column', name: 'id', fieldName: 'id', as: 'id' },
          SQLASTNode {
            args: { ratingGroupID: '1' },
            type: 'table',
            name: 'league_season_user_stats',
            as: 'usersTop',
            orderBy: { rating: 'DESC' },
            children:
             [ { type: 'composite',
                 name: [ 'season_id', 'user_id' ],
                 fieldName: 'sea#use',
                 as: 'sea#use' },
               SQLASTNode {
                 type: 'columnDeps',
                 names: { season_id: 'season_id', user_id: 'user_id' },
                 fromOtherTable: null } ],
            fieldName: 'usersTop',
            grabMany: true,
            where: [Function: where],
            sqlBatch:
             { thisKey:
                { type: 'column',
                  name: 'season_id',
                  fieldName: 'season_id',
                  as: 'season_id' },
               parentKey: { type: 'column', name: 'id', fieldName: 'id', as: 'id' } } } ],
       fieldName: 'seasons',
       grabMany: true,
       sqlJoin: [Function: sqlJoin] } ],
  fieldName: 'league',
  grabMany: false,
  where: [Function: where] } +0ms
  join-monster
  join-monster SQL
  join-monster  SELECT
  "league"."id" AS "id",
  "seasons"."id" AS "seasons__id"
FROM leagues "league"
LEFT JOIN league_seasons "seasons" ON "seasons".league_id = "league".id
WHERE "league".game_id = 2 AND "league".region_id = 1 +3ms
  join-monster
  join-monster SHAPE_DEFINITION
  join-monster  { id: 'id', seasons: [ { id: 'seasons__id' } ] } +1ms
  join-monster
  join-monster RAW DATA
  join-monster  [ anonymous { id: 2, seasons__id: 2 } ] +387ms
  join-monster 1 rows... +0ms
  join-monster
  join-monster SHAPED_DATA
  join-monster  { id: 2, seasons: [ { id: 2 } ] } +2ms
  join-monster
  join-monster SQL_AST
  join-monster  SQLASTNode {
  args: { ratingGroupID: '1' },
  type: 'table',
  name: 'league_season_user_stats',
  as: 'usersTop',
  orderBy: { rating: 'DESC' },
  children:
   [ { type: 'composite',
       name: [ 'season_id', 'user_id' ],
       fieldName: 'sea#use',
       as: 'sea#use' },
     SQLASTNode {
       type: 'columnDeps',
       names: { season_id: 'season_id', user_id: 'user_id' },
       fromOtherTable: null },
     { type: 'column',
       name: 'season_id',
       fieldName: 'season_id',
       as: 'season_id' } ],
  fieldName: 'usersTop',
  grabMany: true,
  where: [Function: where],
  sqlBatch:
   { thisKey:
      { type: 'column',
        name: 'season_id',
        fieldName: 'season_id',
        as: 'season_id' },
     parentKey: { type: 'column', name: 'id', fieldName: 'id', as: 'id' } } } +2ms
  join-monster
  join-monster SQL
  join-monster  SELECT
  NULLIF(CONCAT("usersTop"."season_id", "usersTop"."user_id"), '') AS "sea#use",
  "usersTop"."season_id" AS "season_id",
  "usersTop"."user_id" AS "user_id"
FROM league_season_user_stats "usersTop"
WHERE "usersTop".rating_group_id = 1 AND "usersTop"."season_id" IN (2)
ORDER BY "usersTop"."rating" DESC +0ms
  join-monster
  join-monster SHAPE_DEFINITION
  join-monster  [ { 'sea#use': 'sea#use',
    season_id: 'season_id',
    user_id: 'user_id' } ] +1ms
  join-monster
  join-monster RAW DATA
  join-monster  [] +96ms
  join-monster 0 rows... +1ms
  join-monster
  join-monster SHAPED_DATA
  join-monster  [] +0ms
  join-monster
  join-monster SQL_AST
  join-monster  { args: { ratingGroupID: '1' },
  type: 'table',
  name: 'league_season_user_stats',
  as: 'usersTop',
  orderBy: { rating: 'DESC' },
  children:
   [ { type: 'composite',
       name: [ 'season_id', 'user_id' ],
       fieldName: 'sea#use',
       as: 'sea#use' },
     SQLASTNode {
       type: 'columnDeps',
       names: { season_id: 'season_id', user_id: 'user_id' },
       fromOtherTable: null } ],
  fieldName: 'usersTop',
  grabMany: true,
  where: [Function: where],
  sqlBatch:
   { thisKey:
      { type: 'column',
        name: 'season_id',
        fieldName: 'season_id',
        as: 'season_id' },
     parentKey: { type: 'column', name: 'id', fieldName: 'id', as: 'id' } } } +2ms
```

**Comment by Maxpain177** [comment]
@acarl005

**Comment by Maxpain177** [comment]
@acarl005, please
