### ISSUE TITLE
Cannot read property 'as' of null

### ISSUE THREAD

**Issue by neilrjones** [join-monster/join-monster#325]
"join-monster": "^2.0.16",
    "join-monster-graphql-tools-adapter": "^0.0.3",

join-monster output
```  join-monster
  join-monster SQL_AST
  join-monster  { args: {},
  type: 'table',
  name: 'users',
  as: 'me',
  children:
   [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'firstName',
       fieldName: 'firstName',
       as: 'firstName' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'lastName',
       fieldName: 'lastName',
       as: 'lastName' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'username',
       fieldName: 'username',
       as: 'username' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'token',
       fieldName: 'token',
       as: 'token' },
     SQLASTNode {
       args: {},
       type: 'table',
       name: 'billings',
       as: 'billings',
       children:
        [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
          SQLASTNode {
            args: {},
            type: 'column',
            name: 'street',
            fieldName: 'street',
            as: 'street' },
          SQLASTNode {
            args: {},
            type: 'column',
            name: 'state',
            fieldName: 'state',
            as: 'state' },
          SQLASTNode {
            args: {},
            type: 'column',
            name: 'city',
            fieldName: 'city',
            as: 'city' } ],
       fieldName: 'billings',
       grabMany: true,
       junction:
        { sqlTable: 'billusers',
          as: 'billusers',
          sqlJoins: [ [Function], [Function] ] } },
     SQLASTNode { args: {}, type: 'noop' } ],
  fieldName: 'me',
  grabMany: false,
  where: [Function: where] } +0ms
  join-monster
  join-monster SQL
  join-monster  SELECT
  "me"."id" AS "id",
  "me"."firstName" AS "firstName",
  "me"."lastName" AS "lastName",
  "me"."username" AS "username",
  "me"."token" AS "token",
  "billings"."id" AS "billings__id",
  "billings"."street" AS "billings__street",
  "billings"."state" AS "billings__state",
  "billings"."city" AS "billings__city"
FROM users "me"
LEFT JOIN billusers "billusers" ON "me"."userId" = "billusers"."userId"
LEFT JOIN billings "billings" ON "billusers"."userId" = "billings"."userId"
WHERE "me".id = 2 +5ms
  join-monster
  join-monster SHAPE_DEFINITION
  join-monster  { id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  username: 'username',
  token: 'token',
  billings:
   [ { id: 'billings__id',
       street: 'billings__street',
       state: 'billings__state',
       city: 'billings__city' } ] } +2ms
Executing (default): SELECT
  "me"."id" AS "id",
  "me"."firstName" AS "firstName",
  "me"."lastName" AS "lastName",
  "me"."username" AS "username",
  "me"."token" AS "token",
  "billings"."id" AS "billings__id",
  "billings"."street" AS "billings__street",
  "billings"."state" AS "billings__state",
  "billings"."city" AS "billings__city"
FROM users "me"
LEFT JOIN billusers "billusers" ON "me"."userId" = "billusers"."userId"
LEFT JOIN billings "billings" ON "billusers"."userId" = "billings"."userId"
WHERE "me".id = 2
  join-monster
  join-monster RAW DATA
  join-monster  [ { id: 2,
    firstName: 'Franky',
    lastName: 'Masurel',
    username: 'fmasurel1',
    token: 'da4830cc-f60a-4753-873e-1acce46b6ff4',
    billings__id: 2,
    billings__street: '6 Farragut Lane',
    billings__state: '0',
    billings__city: 'Pittsburgh' } ] +13ms
  join-monster 1 rows... +1ms
  join-monster
  join-monster SHAPED_DATA
  join-monster  { id: 2,
  firstName: 'Franky',
  lastName: 'Masurel',
  username: 'fmasurel1',
  token: 'da4830cc-f60a-4753-873e-1acce46b6ff4',
  billings:
   [ { id: 2,
       street: '6 Farragut Lane',
       state: '0',
       city: 'Pittsburgh' } ] } +5ms
  join-monster
  join-monster SQL_AST
  join-monster  { args: {},
  type: 'table',
  name: 'billings',
  as: 'billings',
  children:
   [ { type: 'column', name: 'id', fieldName: 'id', as: 'id' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'street',
       fieldName: 'street',
       as: 'street' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'state',
       fieldName: 'state',
       as: 'state' },
     SQLASTNode {
       args: {},
       type: 'column',
       name: 'city',
       fieldName: 'city',
       as: 'city' } ],
  fieldName: 'billings',
  grabMany: true,
  junction:
   { sqlTable: 'billusers',
     as: 'billusers',
     sqlJoins: [ [Function], [Function] ] } } +2ms
TypeError: Cannot read property 'as' of null
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:139:74
    at Generator.next (<anonymous>)
    at step (D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:191)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:437
    at new Promise (<anonymous>)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:99
    at handleTable (D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:175:18)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:13:15
    at Generator.next (<anonymous>)
    at step (D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:191)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:437
    at new Promise (<anonymous>)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:99
    at _stringifySqlAST (D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:61:18)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:203:56
    at Generator.next (<anonymous>)
    at step (D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:191)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:437
    at new Promise (<anonymous>)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:191:99
    at stringifySqlAST (D:\node-dev\sousou-server\node_modules\join-monster\dist\stringifiers\dispatcher.js:224:18)
    at D:\node-dev\sousou-server\node_modules\join-monster\dist\util.js:31:47
POST /graphql 200 76.493 ms - 133```
[graphql.zip](https://github.com/stems/join-monster/files/2020397/graphql.zip)

**Comment by GlennMatthys** [comment]
Do you have a more complete code sample that we can reproduce this error with on our side?

**Comment by nicoabie** [comment]
Please provide running example using https://github.com/join-monster/join-monster-sscce
