### ISSUE TITLE
Lists of GraphQLNonNull items not working

### ISSUE THREAD

**Issue by maxpain** [join-monster/join-monster#64]
Part of schema:
```javascript
const QueryRoot = new GraphQLObjectType({
	name: 'Query',
	fields: () => ({
		friends: {
			type: new GraphQLList(new GraphQLNonNull(Friend))
		}
	})
})
```

Error:
```json
{
  "data": null,
  "errors": [
    {
      "message": "Cannot read property 'length' of undefined",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "friends"
      ]
    }
  ]
}
```

Stacktrace:
```
  API TypeError: Cannot read property 'length' of undefined
  API     at pruneDuplicateSqlDeps (/Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/queryASTToSqlAST.js:263:24)
  API     at Object.queryASTToSqlAST (/Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/queryASTToSqlAST.js:35:3)
  API     at /Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/index.js:9:29
  API     at Generator.next (<anonymous>)
  API     at step (/Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/index.js:117:191)
  API     at /Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/index.js:117:437
  API     at /Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/index.js:117:99
  API     at joinMonster (/Users/maxpain/dev/projects/fastcup/backend/node_modules/join-monster/dist/index.js:17:17)
  API     at resolve (/Users/maxpain/dev/projects/fastcup/backend/.build/webpack:/src/schemas/index.js:71:12)
  API     at resolveOrError (/Users/maxpain/dev/projects/fastcup/backend/node_modules/graphql/execution/execute.js:474:12)
  API     at resolveField (/Users/maxpain/dev/projects/fastcup/backend/node_modules/graphql/execution/execute.js:460:16)
  API     at /Users/maxpain/dev/projects/fastcup/backend/node_modules/graphql/execution/execute.js:274:18
  API     at Array.reduce (native)
  API     at executeFields (/Users/maxpain/dev/projects/fastcup/backend/node_modules/graphql/execution/execute.js:271:42)
  API     at executeOperation (/Users/maxpain/dev/projects/fastcup/backend/node_modules/graphql/execution/execute.js:212:10)
  API     at /Users/maxpain/dev/projects/fastcup/backend/node_modules/graphql/execution/execute.js:120:13
  API     at Object.execute (/Users/maxpain/dev/projects/fastcup/backend/node_modules/graphql/execution/execute.js:119:10)
  API     at doRunQuery (/Users/maxpain/dev/projects/fastcup/backend/node_modules/apollo-server/src/core/runQuery.ts:126:16)
  API     at resolvedPromise.then (/Users/maxpain/dev/projects/fastcup/backend/node_modules/apollo-server/src/core/runQuery.ts:59:39)
  API     at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by acarl005** [comment]
Fixed in latest version **v0.9.7**. Thanks!
