### ISSUE TITLE
getting the count of the records using join-monster for root level type 

### ISSUE THREAD

**Issue by praseedasathaye** [join-monster/join-monster#93]
This is a very common use case in every UI that we have.

UseCase - Get the count of the records along with the records.
```
{
  Items (itemSource:"Cash"{ 
    Count
    expenseItems {
       ExpenseId
       PersonId
    #...
  }
}
```

I need the below way (sqlColumn: 'count(*)') to get the count. Is this supported?
```
const ExpenseCount = new GraphQLObjectType({
  description: 'Cash Expense Items',
  name: 'ExpenseCount',
  sqlTable: 'EXM_EXPENSES',
  uniqueKey: 'EXPENSE_ID',
  fields: () => ({
    Count: {
      type: GraphQLInt,
      description: 'Count of Expense Items',
      sqlColumn: 'count(*)'
    }
  })
})
```

I tried in different ways but none works. Not sure if join-monster supports the count at root type?

Approach 1:
Tried adding the count to the Connection and it gives me an error. Also it does not print the arguments in the below block which is passed in the graphql query

```
Const connectionConfig = { nodeType: Expense }
if (PAGINATE === 'offset') {
  connectionConfig.connectionFields = {
    Count: {
      type: GraphQLInt,
      description: 'Count of Cash Expense Items',
      sqlExpr: table => `(SELECT count(*) FROM EXM_EXPENSES WHERE EXPENSE_SOURCE = 'CASH')`,
      resolve: async (parent, args, context, resolveInfo) => {
          console.log("print in the connection: " + args.expenseSource)
          return joinMonster(resolveInfo, context, sql => dbCall(sql, knex, context), options)
        } 
    }
  }
}
const { connectionType: ExpenseConnection } = connectionDefinitions(connectionConfig)
export { Expense, ExpenseConnection }
```
Error that I get is.
```
{ AssertionError: Must call joinMonster in a resolver on a field where the type is decorated with "sqlTable".
    at Object.queryASTToSqlAST (node_modules/join-monster/dist/queryASTToSqlAST.js:37:20)
    at node_modules/join-monster/dist/index.js:9:29
    at Generator.next (<anonymous>)
    at step (node_modules/join-monster/dist/index.js:85:191)
    at node_modules/join-monster/dist/index.js:85:437
    at node_modules/join-monster/dist/index.js:85:99
    at joinMonster (node_modules/join-monster/dist/index.js:19:17)
    at schema/Expense.js:167:18
    at Generator.next (<anonymous>)
    at step (schema/Expense.js:50:191)
    at schema/Expense.js:50:437
    at schema/Expense.js:50:99
    at resolve (schema/Expense.js:165:7)
    at resolveOrError (node_modules/graphql/execution/execute.js:454:12)
    at resolveField (node_modules/graphql/execution/execute.js:445:16)
    at node_modules/graphql/execution/execute.js:252:18
  message: 'Must call joinMonster in a resolver on a field where the type is decorated with "sqlTable".',
  locations: [ { line: 17, column: 5 } ],
  path: [ 'items', 'Count' ] }
```
Approach 2:
Created a new Type just for count

```
const ExpenseCount = new GraphQLObjectType({
  description: 'Cash Expense Items',
  name: 'ExpenseCount',
  sqlTable: 'EXM_EXPENSES',
  uniqueKey: 'EXPENSE_ID',
  fields: () => ({
    Count: {
      type: GraphQLInt,
      description: 'Count of Expense Items',
      sqlExpr: table => `(SELECT count(*) FROM EXM_EXPENSES)`
    }
  })
})
```

Here is my queryroot

```
    countItems: {
        type: ExpenseCount,
        args: {
          expenseSource: {
              type: GraphQLString 
           }
        },
        where: (itemsTable, args, context) => { // eslint-disable-line no-unused-vars
              return `${itemsTable}.EXPENSE_SOURCE = 'CASH'
          }
```
It gives me wrong count as the below query is not formed correct. I need to append the where clause to this sqlExpr but it does inner query.

```
SELECT
  "a"."EXPENSE_ID" AS "b",
  (SELECT count(*) FROM EXM_EXPENSES) AS "c"
FROM EXM_EXPENSES "a"
WHERE "a".EXPENSE_SOURCE = 'CASH'
```
I want this query to be executed

```
SELECT count(*) FROM EXM_EXPENSES a WHERE "a".EXPENSE_SOURCE = 'CASH'
```

**Comment by acarl005** [comment]
Since this is a very simple query which is just returning a number, no JOINs or hydrating objects involved, there is no benefit to going through Join Monster. The best thing to do is write the query manually and submit to the database driver directly.

**Comment by chaim0m** [comment]
How would I define this field `total` as part of a resolver that uses Join-monster? Right now my resolver looks like this:
```const joinMonster = require("join-monster").default; 
const sql = require("mssql"); 

export const  studentsPageResolver = async(obj, { filter }, context, info) => {
    return {
      students: ()=> joinMonster(
        info,
        context,
        async sqlString => {
            console.log(sqlString);
            const results = await sql.query([sqlString]);
            return results.recordset;
        },
    ),
    total: async ()=> {
        const schools = filter.schoolIds.toString();
        const result =  await sql.query([`select count (*)
        FROM [JLIC].[dbo].[StudentView] WHERE SchoolID IN (${schools})`])
        const number = result.recordset[0][''];
        return number;
      }
  }
}
```
But I keep on getting this error:
"Must call joinMonster in a resolver on a field where the type is decorated with "sqlTable"."
